### PR TITLE
Catch nil dates

### PR DESCRIPTION
**Pull request by saizai**

### CODE REVIEW

**Comment by saizai** [comment]
@dwillis ?

**Comment by dwillis** [comment]
Not sure how this differs from the existing code, which still returns nil for a nil date value. Can you give me an example that shows why it's needed?

**Comment by saizai** [comment]
In Rubinius:
```
> Date.parse(nil)
TypeError: can't dup NilClass
	from kernel/common/immediate.rb:25:in `dup'
```

**Comment by dwillis** [comment]
Ah, ok. Right now FEC doesn't support Rubinius, but I'd be open to a PR that does that, not just for date parsing, but for the entire library.

**Comment by saizai** [comment]
I'm using it in Rubinius right now, importing everything from the first v3
record onwards. I'll PR as needed, but so far nothing else is Rubinius
related AFAICT.

**Comment by dwillis** [comment]
Ok - if the other specs pass in Rubinius and this is the only fix needed, that would be great.

**Comment by saizai** [comment]
Done. See https://github.com/NYTimes/Fech/pull/72

**Comment by saizai** [comment]
@dwillis Any reason not to merge this now? It's at worst equivalent to previous functionality, and fixes it on Rubinius.

**Pull request merged**
